version: '3.1'

services:

  airline-app:
   image: devcamp-airline:v1
   ports:
     - "8080:8080"
   environment:
      SPRING_DATASOURCE_URL: "jdbc:postgresql://db:5432/flight_company"
   depends_on:
     - db


  db:
    image: postgres
    container_name: company-postgres
    restart: always
    ports:
      - "8432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flight_company


  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080