version: '3.1'

services:

  db:
    image: postgres
    container_name: company-postgres
    restart: always
    ports:
      - "8432:5432"
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: flight_company


  adminer:
    image: adminer
    restart: always
    ports:
      - 9080:8080